# 1. Fonctions #

In [ ]:
f = lambda x, y: x**2 + y
print(f(3,2))

In [ ]:
def e_potentielle(masse, hauteur, e_limite, g):
    E = masse * hauteur * g
    print(E, 'Joules')
    print('Supérieure ?', E >= e_limite)
    return E

In [ ]:
resultat = e_potentielle(10, 8, 6000, 9.81)

# 2. Conditions et Boucles #

In [ ]:
def signe(x):
    if (x > 0):
        print(x, 'positif')
    elif (x == 0):
        print(x, 'nul')
    else:
        print(x, 'négatif')

In [ ]:
signe(1)

In [ ]:
for i in range(10, -10, -3):
    signe(i)

In [ ]:
x = 0
while (x < 10):
    print(x)
    x += 2

In [ ]:
def fibonacci(n):
    i = 0
    j = 1
    while (i < n):
        print(i)
        i, j = j, i + j

In [ ]:
fibonacci(400)

# 3. Séquences #

In [ ]:
liste_1 = [1, 4, 2, 7, 35, 84]
villes = ['Paris', 'Berlin', 'Londres', 'Bruxelles']
liste_2 = [liste_1, villes]
liste_3 = []

In [ ]:
tuple_1 = (1, 2, 6, 1, 7)

In [ ]:
prenom = 'Nicolas'

In [ ]:
print(villes[0])
print(villes[1])

print(villes[-1])

In [ ]:
print(villes[:3])
print(villes[2:])
print(villes[1::2])

print(prenom[:3])
villes[0] = 'Dublin'
print(villes)

In [ ]:
villes[0] = 'Paris'
villes.append('Dublin')
villes

In [ ]:
villes.insert(2, 'Madrid')
villes

In [ ]:
villes_2 = ['Amsterdam', 'Rome']
villes.extend(villes_2)
villes

In [ ]:
len(villes)

In [ ]:
villes.sort(reverse = True)
print(villes)

liste_1.sort()
print(liste_1)

In [ ]:
villes[3] = 'Paris'
villes.count('Paris')

In [ ]:
if 'Belfast' in villes:
    print('Oui')
else:
    print('Non')

In [ ]:
for i in villes:
    print(i)

In [ ]:
for i, valeur in enumerate(villes):
    print(i, valeur)

In [ ]:
for a, b in zip(villes, liste_1):
    print(a, b)

In [ ]:
def fibonacci(n):
    suite = []
    i = 0
    j = 1
    while (i < n):
        suite.append(i)
        i, j = j, i + j
    return suite

In [ ]:
fibonacci(1000)

# 4. Dictionnaires #

In [121]:
traduction = {
    "chien" : "dog",
    "chat" : "cat",
    "souris" : "mouse",
    "oiseau" : "bird"
}

In [122]:
inventaire = {
    "banane" : 5000,
    "pommes" : 2094,
    "poires" : 425,
    "cerises" : 2893
}

In [123]:
dictionnaire_3 = {
    "dict_1" : traduction,
    "dict_2" : inventaire
}

In [124]:
import numpy as np
paramètres = {
    "W1" : np.random.randn(10, 100),
    "b1" : np.random.randn(10, 1),
    "W2" : np.random.randn(10, 10),
    "b2" : np.random.randn(10, 1)
}

In [125]:
inventaire.values()

dict_values([5000, 2094, 425, 2893])

In [126]:
inventaire.keys()

dict_keys(['banane', 'pommes', 'poires', 'cerises'])

In [127]:
len(inventaire)

4

In [ ]:
inventaire["abricots"] = 4902
inventaire

In [ ]:
print(inventaire.get("peches", 1))

In [ ]:
liste_1 = ("Paris", "Londres", "Bruxelles")
inventaire.fromkeys(liste_1, "defaut")

In [ ]:
inventaire.pop("abricots")

In [ ]:
inventaire

In [ ]:
for i in inventaire.values():
    print(i)

In [ ]:
for k, v in inventaire.items():
    print(k, v)

In [ ]:
classeur = {
    "positif" : [],
    "négatif" : []
}

In [ ]:
def trier(classeur, nombre):
    if (nombre > 0):
        classeur.get("positif").append(nombre)
    else:
        classeur.get("négatif").append(nombre)
    return classeur


In [ ]:
trier(classeur, 9)

# 5. Comprehension #

In [ ]:
import time

In [ ]:
# carrés de 0 à 9 #

start = time.time()

liste_1 = []
for i in range(10000):
    liste_1.append(i**2)

end = time.time()

print(end - start)

In [ ]:
start = time.time()

liste_2 = [i**2 for i in range(10000)]

end = time.time()

print(end - start)

In [ ]:
liste_3 = [[i + j for i in range(3)] for j in range(3)]
liste_3

In [ ]:
dictionnaire = {
    "0" : "Pierre",            
    "1" : "Jean",
    "2" : "Julie",
    "3" : "Sophie"
}

In [ ]:
prénoms = ["Pierre", "Jean", "Julie", "Sophie"]

In [ ]:
dico = {k : v for k, v in enumerate(prénoms)}
print(dico)

In [ ]:
dico.values()

In [ ]:
ages = [24, 62, 10, 23]

In [ ]:
dico_2 = {prénom : age for prénom, age in zip(prénoms, ages) if age > 20}
print(dico_2)

In [ ]:
tuple_1 = tuple((i**2 for i in range(10)))
tuple_1

In [ ]:
clés = [i for i in range(21)]
valeurs = [j**2 for j in range(21)]
dico_exo = {clé : valeur for clé, valeur in zip(clés, valeurs)}

print(dico_exo)

In [ ]:
dico_exo2 = {i : i**2 for i in range(21)}

print(dico_exo2)

# 6. Built-in functions #

In [ ]:
x = -2
abs(x)

In [ ]:
liste_1 = [0, 23, 14, -19]

In [ ]:
max(liste_1)

In [ ]:
min(liste_1)

In [ ]:
len(liste_1)

In [ ]:
sum(liste_1)

In [ ]:
liste_2 = [True, True, False]

In [ ]:
any(liste_2)

In [ ]:
all(liste_2)

In [ ]:
any(liste_1)

In [ ]:
all(liste_1)

### Conversions ###

In [ ]:
x = 10
type(x)

In [ ]:
x = str(x)
x

In [ ]:
type(x)

In [ ]:
y = "20"
y = int(y)
y

In [ ]:
type(y)

In [ ]:
x = 10
type(float(x))

In [ ]:
liste_1 = [0, 61, 63, 243]

In [ ]:
tuple_1 = tuple(liste_1)

In [ ]:
list(tuple_1)

In [ ]:
inventaire = {
    "banane" : 5000,
    "pommes" : 2094,
    "poires" : 425
}

In [ ]:
list(inventaire.keys())

In [ ]:
bin(15)

In [ ]:
oct(15)

In [ ]:
hex(15)

### Input ###

In [1]:
input()

 hey


'hey'

In [2]:
x = input("entrez un nombre : ")

entrez un nombre :  5


In [3]:
type(x)

str

In [4]:
int(x) + 10

15

### Format ###

In [5]:
x = 25
ville = "Paris"

message = "la temp est de {} degC à {}".format(x, ville)

print(message)

la temp est de 25 degC à Paris


In [7]:
message_2 = f"la temp est de {x} degC à {ville}"
print(message_2)

la temp est de 25 degC à Paris


In [11]:
paramètres = {
    "W1" : np.random.randn(2, 4),
    "b1" : np.random.randn(2, 1),
    "W2" : np.random.randn(2, 2),
    "b2" : np.random.randn(2, 1)
}

for i in range(1, 3):
    print("couche", i)
    print(paramètres["W{}".format(i)])

couche 1
[[ 0.3445534  -0.19861275 -0.60217583  1.86702754]
 [-1.24734074  0.03206686 -0.00634906 -1.86410522]]
couche 2
[[-0.92459801 -1.66849157]
 [ 1.7348825  -0.99479328]]


### Open ###

In [3]:
f = open("001 - fichier.txt", "w")

In [4]:
f.write("bonjour")
f.close()

In [5]:
f = open("001 - fichier.txt", "r")
f.read()

'bonjour'

In [6]:
with open("001 - fichier.txt", "r") as f:
    print(f.read())

bonjour


In [7]:
with open("001 - fichier.txt", "w") as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i, i**2))

In [8]:
with open("001 - fichier.txt", "r") as f:
    print(f.read().splitlines())

['0^2 = 0 ', '1^2 = 1 ', '2^2 = 4 ', '3^2 = 9 ', '4^2 = 16 ', '5^2 = 25 ', '6^2 = 36 ', '7^2 = 49 ', '8^2 = 64 ', '9^2 = 81 ']


In [9]:
liste = [line.strip() for line in open('001 - fichier.txt', 'r')]
liste

['0^2 = 0',
 '1^2 = 1',
 '2^2 = 4',
 '3^2 = 9',
 '4^2 = 16',
 '5^2 = 25',
 '6^2 = 36',
 '7^2 = 49',
 '8^2 = 64',
 '9^2 = 81']

# 7. Modules #

In [13]:
import math
import statistics
import random
import os
import glob

In [50]:
print(math.cos(2*math.pi))
print(math.exp(5))

1.0
148.4131591025766


In [51]:
liste_1 = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [53]:
print(statistics.mean(liste_1))
print(statistics.variance(liste_1))

8.8
121.73333333333333


In [57]:
print(random.choice(["Jean", "Anne", "Julie"]))

Julie


In [60]:
random.seed(0)
print(random.choice(["Jean", "Anne", "Julie"]))

Anne


In [69]:
print(random.random())
print(random.randint(5, 10))
print(random.randrange(100))

0.48592769656281265
7
61


In [72]:
print(random.sample(range(100), 10))
print(random.sample(range(100), random.randrange(10)))

[60, 71, 12, 45, 55, 40, 78, 81, 26, 70]
[56, 66, 33, 7, 70, 1, 11]


In [74]:
random.shuffle(liste_1)
print(liste_1)

[1, 2, 3, 13, 1, 21, 34, 0, 8, 5]


In [79]:
os.getcwd()

'C:\\Users\\asus'

In [97]:
filenames = glob.glob("*.txt")

In [98]:
for file in filenames:
    with open(file, 'r') as f:
        print(f.read())

0^2 = 0 
1^2 = 1 
2^2 = 4 
3^2 = 9 
4^2 = 16 
5^2 = 25 
6^2 = 36 
7^2 = 49 
8^2 = 64 
9^2 = 81 

Paris Londres Madrid


In [10]:
f = open("001 - fichier_1.txt", "w")
f.write("Paris " + "Londres " + "Madrid")

20

In [11]:
f = open("001 - fichier_1.txt", "r")
f.read()

'Paris Londres Madrid'

In [14]:
filenames = glob.glob("*.txt")
dico_exo = {}

for file in filenames:
    with open(file, 'r') as f:
        dico_exo[file] = f.read().splitlines()

print(dico_exo)

{'000 - fichier.txt': [], '001 - fichier.txt': ['0^2 = 0 ', '1^2 = 1 ', '2^2 = 4 ', '3^2 = 9 ', '4^2 = 16 ', '5^2 = 25 ', '6^2 = 36 ', '7^2 = 49 ', '8^2 = 64 ', '9^2 = 81 '], '001 - fichier_1.txt': ['Paris Londres Madrid']}
