In [40]:
import numpy as np
import torch
import torchvision

# Creation

In [9]:
x = torch.empty(2, 2, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [10]:
x = torch.rand(2, 2)
print(x)

tensor([[0.9195, 0.5168],
        [0.3958, 0.5558]])


In [12]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [13]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
print(x.dtype)

torch.float32


In [17]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [18]:
print(x.size())

torch.Size([2, 2])


In [19]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# Operations

In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.7008, 0.3449],
        [0.0085, 0.2039]])
tensor([[0.2841, 0.6180],
        [0.0628, 0.6025]])


In [21]:
z = x + y
print(z)

tensor([[0.9849, 0.9630],
        [0.0713, 0.8064]])


In [22]:
z = torch.add(x, y)
print(z)

tensor([[0.9849, 0.9630],
        [0.0713, 0.8064]])


In [23]:
y.add_(x)
print(y)

tensor([[0.9849, 0.9630],
        [0.0713, 0.8064]])


In [24]:
z = torch.sub(x, y)
print(z)

tensor([[-0.2841, -0.6180],
        [-0.0628, -0.6025]])


In [25]:
z = torch.mul(x, y)
print(z)

tensor([[6.9029e-01, 3.3217e-01],
        [6.0769e-04, 1.6445e-01]])


In [26]:
z = torch.div(x, y)
print(z)

tensor([[0.7116, 0.3582],
        [0.1195, 0.2529]])


In [33]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())

tensor([[0.3380, 0.5527, 0.5486],
        [0.6680, 0.9593, 0.2290],
        [0.2560, 0.7156, 0.7218],
        [0.9606, 0.9552, 0.6190],
        [0.7714, 0.5415, 0.9155]])
tensor([0.3380, 0.6680, 0.2560, 0.9606, 0.7714])
tensor([0.6680, 0.9593, 0.2290])
0.9593074917793274


In [39]:
x = torch.rand(4, 4)
print(x)
y = x.view(-1, 8)
print(y.size())

tensor([[0.0064, 0.5730, 0.5051, 0.8546],
        [0.7010, 0.6828, 0.2412, 0.9849],
        [0.8857, 0.0125, 0.1645, 0.5417],
        [0.0608, 0.0064, 0.1044, 0.7780]])
torch.Size([2, 8])


# Numpy

In [57]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [58]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [59]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [63]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [64]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [66]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = np.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.numpy()

In [67]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
