In [2]:
import torch

In [49]:
x = torch.randn(3, requires_grad=True)

In [50]:
y = x + 2
print(y)

tensor([1.7965, 1.8589, 0.6600], grad_fn=<AddBackward0>)


In [51]:
z = y*y*2
print(z)

tensor([6.4551, 6.9107, 0.8713], grad_fn=<MulBackward0>)


In [52]:
#z = z.mean()
print(z)

tensor([6.4551, 6.9107, 0.8713], grad_fn=<MulBackward0>)


In [53]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([7.1862e-01, 7.4354e+00, 2.6402e-03])


In [48]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x.requires_grad_(False)
print(x)

tensor([-0.2267, -1.2287,  1.2859])


In [54]:
y = x.detach()
print(y)

tensor([-0.2035, -0.1411, -1.3400])


In [56]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.7965, 1.8589, 0.6600])


In [59]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [62]:
# weights = torch.ones(4, requires_grad=True)
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()