### Outline

* Implementation of GAT

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# Structure

In [2]:
class GATLayer(nn.Module):
    
    def __init__(self):
        super(GATLayer, self).__init__()
        
    def forward(self, input, adj):
        print("")

# Forward Method 

### Linear Transformation

$$
\bar{h'}_i = \textbf{W}\cdot \bar{h}_i
$$
with $\textbf{W}\in\mathbb R^{F'\times F}$ and $\bar{h}_i\in\mathbb R^{F}$.

$$
\bar{h'}_i \in \mathbb{R}^{F'}
$$

In [3]:
in_features = 5
out_features = 2
nb_nodes = 3

W = nn.Parameter(torch.zeros(size=(in_features, out_features))) #xavier paramiter inizializator
nn.init.xavier_uniform_(W.data, gain=1.414)

input = torch.rand(nb_nodes,in_features) 


# linear transformation
h = torch.mm(input, W)
N = h.size()[0]

print(h.shape)

torch.Size([3, 2])


![title](fig/AttentionMechanism.png)

In [4]:
a = nn.Parameter(torch.zeros(size=(2*out_features, 1))) #xavier paramiter inizializator
nn.init.xavier_uniform_(a.data, gain=1.414)
print(a.shape)

leakyrelu = nn.LeakyReLU(0.2)  # LeakyReLU

torch.Size([4, 1])


In [5]:
a_input = torch.cat([h.repeat(1, N).view(N * N, -1), h.repeat(N, 1)], dim=1).view(N, -1, 2 * out_features)

![title](fig/a_input.png)

In [6]:
e = leakyrelu(torch.matmul(a_input, a).squeeze(2))

In [7]:
print(a_input.shape,a.shape)
print("")
print(torch.matmul(a_input,a).shape)
print("")
print(torch.matmul(a_input,a).squeeze(2).shape)

torch.Size([3, 3, 4]) torch.Size([4, 1])

torch.Size([3, 3, 1])

torch.Size([3, 3])


In [8]:
e

tensor([[-0.0666, -0.2438, -0.0851],
        [-0.2803, -0.4576, -0.2988],
        [-0.0930, -0.2703, -0.1115]], grad_fn=<LeakyReluBackward0>)

### Masked Attention

In [9]:
# Masked Attention
adj = torch.randint(2, (3, 3))

zero_vec  = -9e15*torch.ones_like(e)
print(zero_vec.shape)

torch.Size([3, 3])


In [10]:
attention = torch.where(adj > 0, e, zero_vec)
print(adj,"\n",e,"\n",zero_vec)
attention

tensor([[0, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]) 
 tensor([[-0.0666, -0.2438, -0.0851],
        [-0.2803, -0.4576, -0.2988],
        [-0.0930, -0.2703, -0.1115]], grad_fn=<LeakyReluBackward0>) 
 tensor([[-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15, -9.0000e+15]])


tensor([[-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-2.8030e-01, -4.5756e-01, -2.9883e-01],
        [-9.0000e+15, -2.7027e-01, -9.0000e+15]], grad_fn=<SWhereBackward0>)

In [11]:
attention = F.softmax(attention, dim=1)
h_prime   = torch.matmul(attention, h)

In [12]:
attention

tensor([[0.3333, 0.3333, 0.3333],
        [0.3547, 0.2971, 0.3482],
        [0.0000, 1.0000, 0.0000]], grad_fn=<SoftmaxBackward0>)

In [13]:
h_prime

tensor([[-0.3083,  1.0474],
        [-0.3603,  1.0765],
        [ 0.6396,  0.5163]], grad_fn=<MmBackward0>)

In [14]:
print(h_prime,"\n",h)

tensor([[-0.3083,  1.0474],
        [-0.3603,  1.0765],
        [ 0.6396,  0.5163]], grad_fn=<MmBackward0>) 
 tensor([[-0.8573,  1.3459],
        [ 0.6396,  0.5163],
        [-0.7073,  1.2802]], grad_fn=<MmBackward0>)


# Bulid the layer

In [15]:
class GATLayer(nn.Module):
    def __init__(self, in_features, out_features, dropout, alpha, concat=True):
        super(GATLayer, self).__init__()
        self.dropout       = dropout        # drop prob = 0.6
        self.in_features   = in_features    # 
        self.out_features  = out_features   # 
        self.alpha         = alpha          # LeakyReLU with negative input slope, alpha = 0.2
        self.concat        = concat         # conacat = True for all layers except the output layer.
    
        
    def forward(self, input, adj):
        # Linear Transformation
        h = torch.mm(input, self.W) # matrix multiplication
        N = h.size()[0]

        # Attention Mechanism
        a_input = torch.cat([h.repeat(1, N).view(N * N, -1), h.repeat(N, 1)], dim=1).view(N, -1, 2 * self.out_features)
        e       = self.leakyrelu(torch.matmul(a_input, self.a).squeeze(2))

        # Masked Attention
        zero_vec  = -9e15*torch.ones_like(e)
        attention = torch.where(adj > 0, e, zero_vec)
        
        attention = F.softmax(attention, dim=1)
        attention = F.dropout(attention, self.dropout, training=self.training)
        h_prime   = torch.matmul(attention, h)

        if self.concat:
            return F.elu(h_prime)
        else:
            return h_prime

# Use

In [16]:
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T

import matplotlib.pyplot as plt

name_data = 'Cora'
dataset = Planetoid(root= '/tmp/' + name_data, name = name_data)
dataset.transform = T.NormalizeFeatures()

print(f"Number of Classes in {name_data}:", dataset.num_classes)
print(f"Number of Node Features in {name_data}:", dataset.num_node_features)

Processing...


Number of Classes in Cora: 7
Number of Node Features in Cora: 1433


Done!


In [18]:
class GAT(torch.nn.Module):
    def __init__(self):
        super(GAT, self).__init__()
        self.hid = 8
        self.in_head = 8
        self.out_head = 1
        
        
        self.conv1 = GATConv(dataset.num_features, self.hid, heads=self.in_head, dropout=0.6)
        self.conv2 = GATConv(self.hid*self.in_head, dataset.num_classes, concat=False,
                             heads=self.out_head, dropout=0.6)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
                
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv1(x, edge_index)
        x = F.elu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        
        return F.log_softmax(x, dim=1)
    
    
    
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = "cpu"

model = GAT().to(device)
data = dataset[0].to(device)


optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

model.train()
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    
    if epoch%20 == 0:
        print(loss)
    
    loss.backward()
    optimizer.step()

tensor(1.9448, grad_fn=<NllLossBackward0>)
tensor(1.7852, grad_fn=<NllLossBackward0>)
tensor(1.5120, grad_fn=<NllLossBackward0>)
tensor(1.3268, grad_fn=<NllLossBackward0>)
tensor(1.0838, grad_fn=<NllLossBackward0>)


In [19]:
model.eval()
_, pred = model(data).max(dim=1)
correct = float(pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))

Accuracy: 0.8160
